// <auto-generated />
using System;
using Matrimonial.AdminApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matrimonial.AdminApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260816125414_LowercasePostgresIdentifiers")]
    partial class LowercasePostgresIdentifiers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("adminid");

                    b.Property<string>("AdminUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("adminusername");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firstname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastlogin");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedon");

                    b.HasKey("AdminId")
                        .HasName("pk_adminusers");

                    b.HasIndex("AdminUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_adminusers_adminusername");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_adminusers_email");

                    b.ToTable("adminusers", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.EmailTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("templateid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("templatename");

                    b.HasKey("TemplateId")
                        .HasName("pk_emailtemplates");

                    b.HasIndex("TemplateName")
                        .IsUnique()
                        .HasDatabaseName("ix_emailtemplates_templatename");

                    b.ToTable("emailtemplates", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("paymentid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("invoicenumber");

                    b.Property<DateTime?>("PaidOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paidon");

                    b.Property<string>("PaymentGateway")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paymentgateway");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("paymentmethod");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriptionid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transactionid");

                    b.HasKey("PaymentId")
                        .HasName("pk_payments");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_payments_subscriptionid");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_payments_tenantid");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("planid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("durationdays");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("planname");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.HasKey("PlanId")
                        .HasName("pk_subscriptionplans");

                    b.ToTable("subscriptionplans", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("settingid");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("settingkey");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("settingvalue");

                    b.HasKey("SettingId")
                        .HasName("pk_systemsettings");

                    b.HasIndex("SettingKey")
                        .IsUnique()
                        .HasDatabaseName("ix_systemsettings_settingkey");

                    b.ToTable("systemsettings", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("companyname");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("text")
                        .HasColumnName("connectionstring");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("databasename");

                    b.Property<string>("DatabaseServer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("databaseserver");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logourl");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ownername");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.Property<string>("TenantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tenantcode");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedon");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zipcode");

                    b.HasKey("TenantId")
                        .HasName("pk_tenants");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_tenants_createdby");

                    b.HasIndex("TenantCode")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_tenantcode");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.TenantSubscription", b =>
                {
                    b.Property<Guid>("TenantSubscriptionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenantsubscriptionsid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enddate");

                    b.Property<DateTime?>("NextBillingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("nextbillingdate");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("paymentstatus");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("planid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startdate");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subscriptionstatus");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("TenantSubscriptionsId")
                        .HasName("pk_tenantsubscriptions");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_tenantsubscriptions_planid");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenantsubscriptions_tenantid");

                    b.ToTable("tenantsubscriptions", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Payment", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.TenantSubscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_tenantsubscriptions_subscriptionid");

                    b.HasOne("Matrimonial.AdminApi.Entities.Tenant", "Tenant")
                        .WithMany("Payments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_tenants_tenantid");

                    b.Navigation("Subscription");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Tenant", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.AdminUser", "CreatedByAdmin")
                        .WithMany("CreatedTenants")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tenants_adminusers_createdby");

                    b.Navigation("CreatedByAdmin");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.TenantSubscription", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.SubscriptionPlan", "Plan")
                        .WithMany("TenantSubscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenantsubscriptions_subscriptionplans_planid");

                    b.HasOne("Matrimonial.AdminApi.Entities.Tenant", "Tenant")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenantsubscriptions_tenants_tenantid");

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.AdminUser", b =>
                {
                    b.Navigation("CreatedTenants");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("TenantSubscriptions");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Tenant", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.TenantSubscription", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
