// <auto-generated />
using System;
using Matrimonial.AdminApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matrimonial.AdminApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260823100550_AddUserPhotoImageData")]
    partial class AddUserPhotoImageData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<string>("AdminUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("admin_user_name");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("AdminId")
                        .HasName("pk_admin_users");

                    b.HasIndex("AdminUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_admin_user_name");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_email");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.BlockedUser", b =>
                {
                    b.Property<Guid>("BlockedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_id");

                    b.Property<Guid>("BlockedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_user_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("BlockedId")
                        .HasName("pk_blocked_users");

                    b.HasIndex("BlockedUserId")
                        .HasDatabaseName("ix_blocked_users_blocked_user_id");

                    b.HasIndex("UserId", "BlockedUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_blocked_users_user_id_blocked_user_id");

                    b.ToTable("blocked_users", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.EmailTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("template_name");

                    b.HasKey("TemplateId")
                        .HasName("pk_email_templates");

                    b.HasIndex("TemplateName")
                        .IsUnique()
                        .HasDatabaseName("ix_email_templates_template_name");

                    b.ToTable("email_templates", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Favorite", b =>
                {
                    b.Property<Guid>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("favorite_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("FavoriteUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("favorite_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("FavoriteId")
                        .HasName("pk_favorites");

                    b.HasIndex("FavoriteUserId")
                        .HasDatabaseName("ix_favorites_favorite_user_id");

                    b.HasIndex("UserId", "FavoriteUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_favorites_user_id_favorite_user_id");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.InterestRequest", b =>
                {
                    b.Property<Guid>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("interest_id");

                    b.Property<Guid>("ReceiverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_user_id");

                    b.Property<DateTime?>("RespondedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_on");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.Property<DateTime>("SentOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("InterestId")
                        .HasName("pk_interest_requests");

                    b.HasIndex("ReceiverUserId")
                        .HasDatabaseName("ix_interest_requests_receiver_user_id");

                    b.HasIndex("SenderUserId", "ReceiverUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_interest_requests_sender_user_id_receiver_user_id");

                    b.ToTable("interest_requests", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Match", b =>
                {
                    b.Property<Guid>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<decimal>("MatchPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("match_percentage");

                    b.Property<DateTime>("MatchedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("matched_on");

                    b.Property<Guid>("UserId1")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id1");

                    b.Property<Guid>("UserId2")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id2");

                    b.HasKey("MatchId")
                        .HasName("pk_matches");

                    b.HasIndex("UserId2")
                        .HasDatabaseName("ix_matches_user_id2");

                    b.HasIndex("UserId1", "UserId2")
                        .IsUnique()
                        .HasDatabaseName("ix_matches_user_id1_user_id2");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Member", b =>
                {
                    b.Property<Guid>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("photo_status");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_photo_url");

                    b.Property<string>("ProfileStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("profile_status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_code");

                    b.HasKey("MemberId")
                        .HasName("pk_members");

                    b.HasIndex("TenantId", "UserCode")
                        .IsUnique()
                        .HasDatabaseName("ix_members_tenant_id_user_code");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.MemberPlan", b =>
                {
                    b.Property<Guid>("MemberPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("member_plan_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("plan_name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("MemberPlanId")
                        .HasName("pk_member_plans");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_member_plans_tenant_id");

                    b.ToTable("member_plans", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.MemberSubscription", b =>
                {
                    b.Property<Guid>("MemberSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("member_subscription_id");

                    b.Property<DateTime>("AssignedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_on");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid>("MemberPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_plan_id");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("MemberSubscriptionId")
                        .HasName("pk_member_subscriptions");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_member_subscriptions_member_id");

                    b.HasIndex("MemberPlanId")
                        .HasDatabaseName("ix_member_subscriptions_member_plan_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_member_subscriptions_tenant_id");

                    b.ToTable("member_subscriptions", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("ReceiverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_user_id");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.Property<DateTime>("SentOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_on");

                    b.HasKey("MessageId")
                        .HasName("pk_messages");

                    b.HasIndex("ReceiverUserId")
                        .HasDatabaseName("ix_messages_receiver_user_id");

                    b.HasIndex("SenderUserId")
                        .HasDatabaseName("ix_messages_sender_user_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid?>("RelatedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_user_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("invoice_number");

                    b.Property<DateTime?>("PaidOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_on");

                    b.Property<string>("PaymentGateway")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payment_gateway");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transaction_id");

                    b.HasKey("PaymentId")
                        .HasName("pk_payments");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_payments_subscription_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_payments_tenant_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.ProfileView", b =>
                {
                    b.Property<Guid>("ViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("view_id");

                    b.Property<DateTime>("ViewedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewed_on");

                    b.Property<Guid>("ViewedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("viewed_user_id");

                    b.Property<Guid>("ViewerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("viewer_user_id");

                    b.HasKey("ViewId")
                        .HasName("pk_profile_views");

                    b.HasIndex("ViewedUserId")
                        .HasDatabaseName("ix_profile_views_viewed_user_id");

                    b.HasIndex("ViewerUserId")
                        .HasDatabaseName("ix_profile_views_viewer_user_id");

                    b.ToTable("profile_views", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Report", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReportedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_user_id");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("ReportId")
                        .HasName("pk_reports");

                    b.HasIndex("ReportedUserId")
                        .HasDatabaseName("ix_reports_reported_user_id");

                    b.HasIndex("ReporterUserId")
                        .HasDatabaseName("ix_reports_reporter_user_id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("plan_name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.HasKey("PlanId")
                        .HasName("pk_subscription_plans");

                    b.ToTable("subscription_plans", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("setting_id");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("setting_key");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("setting_value");

                    b.HasKey("SettingId")
                        .HasName("pk_system_settings");

                    b.HasIndex("SettingKey")
                        .IsUnique()
                        .HasDatabaseName("ix_system_settings_setting_key");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("text")
                        .HasColumnName("connection_string");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("database_name");

                    b.Property<string>("DatabaseServer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("database_server");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("owner_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.Property<string>("TenantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tenant_code");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zip_code");

                    b.HasKey("TenantId")
                        .HasName("pk_tenants");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_tenants_created_by");

                    b.HasIndex("TenantCode")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_tenant_code");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.TenantSubscription", b =>
                {
                    b.Property<Guid>("TenantSubscriptionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_subscriptions_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime?>("NextBillingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_billing_date");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_status");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subscription_status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("TenantSubscriptionsId")
                        .HasName("pk_tenant_subscriptions");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_tenant_subscriptions_plan_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_subscriptions_tenant_id");

                    b.ToTable("tenant_subscriptions", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_code");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("TenantId", "UserCode")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_user_code");

                    b.HasIndex("TenantId", "UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_user_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserEducation", b =>
                {
                    b.Property<Guid>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("education_id");

                    b.Property<string>("College")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("college");

                    b.Property<string>("EducationType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("education_type");

                    b.Property<int?>("PassingYear")
                        .HasColumnType("integer")
                        .HasColumnName("passing_year");

                    b.Property<string>("Qualification")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("qualification");

                    b.Property<string>("University")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("university");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("EducationId")
                        .HasName("pk_user_educations");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_educations_user_id");

                    b.ToTable("user_educations", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserFamilyDetail", b =>
                {
                    b.Property<Guid>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<int?>("Brothers")
                        .HasColumnType("integer")
                        .HasColumnName("brothers");

                    b.Property<string>("FamilyStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family_status");

                    b.Property<string>("FamilyType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("family_type");

                    b.Property<string>("FatherName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("father_name");

                    b.Property<string>("FatherOccupation")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("father_occupation");

                    b.Property<string>("MotherName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mother_name");

                    b.Property<string>("MotherOccupation")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("mother_occupation");

                    b.Property<int?>("Sisters")
                        .HasColumnType("integer")
                        .HasColumnName("sisters");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("FamilyId")
                        .HasName("pk_user_family_details");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_family_details_user_id");

                    b.ToTable("user_family_details", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserLifestyle", b =>
                {
                    b.Property<Guid>("LifestyleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("lifestyle_id");

                    b.Property<string>("Diet")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("diet");

                    b.Property<bool>("Drinking")
                        .HasColumnType("boolean")
                        .HasColumnName("drinking");

                    b.Property<string>("Hobbies")
                        .HasColumnType("text")
                        .HasColumnName("hobbies");

                    b.Property<string>("LanguagesKnown")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("languages_known");

                    b.Property<bool>("Smoking")
                        .HasColumnType("boolean")
                        .HasColumnName("smoking");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LifestyleId")
                        .HasName("pk_user_lifestyles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_lifestyles_user_id");

                    b.ToTable("user_lifestyles", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserLocation", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("Pincode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pincode");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LocationId")
                        .HasName("pk_user_locations");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_locations_user_id");

                    b.ToTable("user_locations", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserOccupation", b =>
                {
                    b.Property<Guid>("OccupationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("occupation_id");

                    b.Property<decimal?>("AnnualIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("annual_income");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<string>("Designation")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("designation");

                    b.Property<string>("Occupation")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("occupation");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WorkLocation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("work_location");

                    b.HasKey("OccupationId")
                        .HasName("pk_user_occupations");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_occupations_user_id");

                    b.ToTable("user_occupations", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserPhoto", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea")
                        .HasColumnName("image_data");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_on");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("PhotoId")
                        .HasName("pk_user_photos");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_photos_user_id");

                    b.ToTable("user_photos", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("PreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("preference_id");

                    b.Property<string>("Caste")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("caste");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("Education")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("education");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("integer")
                        .HasColumnName("max_age");

                    b.Property<decimal?>("MaxHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("max_height");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer")
                        .HasColumnName("min_age");

                    b.Property<decimal?>("MinHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("min_height");

                    b.Property<string>("Occupation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("occupation");

                    b.Property<string>("Religion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("religion");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("PreferenceId")
                        .HasName("pk_user_preferences");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_preferences_user_id");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("AboutMe")
                        .HasColumnType("text")
                        .HasColumnName("about_me");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("blood_group");

                    b.Property<string>("Caste")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("caste");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<decimal?>("Height")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("height");

                    b.Property<bool>("IsProfileCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_profile_completed");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("marital_status");

                    b.Property<string>("MotherTongue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mother_tongue");

                    b.Property<string>("ProfileStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("profile_status");

                    b.Property<string>("Religion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("religion");

                    b.Property<string>("SubCaste")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sub_caste");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight");

                    b.HasKey("ProfileId")
                        .HasName("pk_user_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profiles_user_id");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Browser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("browser");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_name");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("login_time");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logout_time");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId")
                        .HasName("pk_user_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("UserSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_subscription_id");

                    b.Property<DateTime>("AssignedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_on");

                    b.Property<Guid>("MemberPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_plan_id");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserSubscriptionId")
                        .HasName("pk_user_subscriptions");

                    b.HasIndex("MemberPlanId")
                        .HasDatabaseName("ix_user_subscriptions_member_plan_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_subscriptions_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_subscriptions_user_id");

                    b.ToTable("user_subscriptions", (string)null);
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.BlockedUser", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.User", "Blocked")
                        .WithMany()
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_blocked_users_users_blocked_user_id");

                    b.HasOne("Matrimonial.AdminApi.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_blocked_users_users_user_id");

                    b.Navigation("Blocked");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Favorite", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.User", "FavoriteUser")
                        .WithMany()
                        .HasForeignKey("FavoriteUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_users_favorite_user_id");

                    b.HasOne("Matrimonial.AdminApi.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_users_user_id");

                    b.Navigation("FavoriteUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.InterestRequest", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_interest_requests_users_receiver_user_id");

                    b.HasOne("Matrimonial.AdminApi.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_interest_requests_users_sender_user_id");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Match", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.User", "User1")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_users_user_id1");

                    b.HasOne("Matrimonial.AdminApi.Entities.User", "User2")
                        .WithMany()
                        .HasForeignKey("UserId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_users_user_id2");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Member", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_members_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.MemberPlan", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_plans_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.MemberSubscription", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.Member", "Member")
                        .WithMany("Subscriptions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_subscriptions_members_member_id");

                    b.HasOne("Matrimonial.AdminApi.Entities.MemberPlan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("MemberPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_member_subscriptions_member_plans_member_plan_id");

                    b.HasOne("Matrimonial.AdminApi.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_subscriptions_tenants_tenant_id");

                    b.Navigation("Member");

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Message", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_receiver_user_id");

                    b.HasOne("Matrimonial.AdminApi.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_sender_user_id");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Notification", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Payment", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.TenantSubscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_tenant_subscriptions_subscription_id");

                    b.HasOne("Matrimonial.AdminApi.Entities.Tenant", "Tenant")
                        .WithMany("Payments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_tenants_tenant_id");

                    b.Navigation("Subscription");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.ProfileView", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.User", "Viewed")
                        .WithMany()
                        .HasForeignKey("ViewedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_profile_views_users_viewed_user_id");

                    b.HasOne("Matrimonial.AdminApi.Entities.User", "Viewer")
                        .WithMany()
                        .HasForeignKey("ViewerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_profile_views_users_viewer_user_id");

                    b.Navigation("Viewed");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Report", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.User", "Reported")
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reports_users_reported_user_id");

                    b.HasOne("Matrimonial.AdminApi.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reports_users_reporter_user_id");

                    b.Navigation("Reported");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Tenant", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.AdminUser", "CreatedByAdmin")
                        .WithMany("CreatedTenants")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tenants_admin_users_created_by");

                    b.Navigation("CreatedByAdmin");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.TenantSubscription", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.SubscriptionPlan", "Plan")
                        .WithMany("TenantSubscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_subscriptions_subscription_plans_plan_id");

                    b.HasOne("Matrimonial.AdminApi.Entities.Tenant", "Tenant")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_subscriptions_tenants_tenant_id");

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.User", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserEducation", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.User", "User")
                        .WithMany("Educations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_educations_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserFamilyDetail", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.User", "User")
                        .WithOne("Family")
                        .HasForeignKey("Matrimonial.AdminApi.Entities.UserFamilyDetail", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_family_details_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserLifestyle", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.User", "User")
                        .WithOne("Lifestyle")
                        .HasForeignKey("Matrimonial.AdminApi.Entities.UserLifestyle", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_lifestyles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserLocation", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.User", "User")
                        .WithOne("Location")
                        .HasForeignKey("Matrimonial.AdminApi.Entities.UserLocation", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_locations_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserOccupation", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.User", "User")
                        .WithOne("Occupation")
                        .HasForeignKey("Matrimonial.AdminApi.Entities.UserOccupation", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_occupations_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserPhoto", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.User", "User")
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_photos_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserPreference", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.User", "User")
                        .WithOne("Preference")
                        .HasForeignKey("Matrimonial.AdminApi.Entities.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_preferences_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserProfile", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Matrimonial.AdminApi.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserSession", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.UserSubscription", b =>
                {
                    b.HasOne("Matrimonial.AdminApi.Entities.MemberPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("MemberPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_subscriptions_member_plans_member_plan_id");

                    b.HasOne("Matrimonial.AdminApi.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_subscriptions_tenants_tenant_id");

                    b.HasOne("Matrimonial.AdminApi.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_subscriptions_users_user_id");

                    b.Navigation("Plan");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.AdminUser", b =>
                {
                    b.Navigation("CreatedTenants");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Member", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.MemberPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("TenantSubscriptions");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.Tenant", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.TenantSubscription", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Matrimonial.AdminApi.Entities.User", b =>
                {
                    b.Navigation("Educations");

                    b.Navigation("Family");

                    b.Navigation("Lifestyle");

                    b.Navigation("Location");

                    b.Navigation("Notifications");

                    b.Navigation("Occupation");

                    b.Navigation("Photos");

                    b.Navigation("Preference");

                    b.Navigation("Profile");

                    b.Navigation("Sessions");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
